### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by VEXstar** [seung-lab/fill_voids#4]
When importing a library, I get the following error:
![image](https://user-images.githubusercontent.com/46082448/118289769-1d7f5680-b4ef-11eb-98fb-f857f1f3b7c1.png)

numpy version: 1.19.5

**Comment by william-silversmith** [comment]
Ack, I guess it's time to recompile. Numpy changed its ABI in 1.20, I suppose maybe they did it in 1.19 as well. You can get around this in the mean time by recompiling:

```
pip install fill-voids --no-binary :all: -U
```

**Comment by william-silversmith** [comment]
Oh actually.. that's a problem with `fastremap`, which has recently been recompiled. Run `pip install fastremap -U`. That should solve it.

**Comment by VEXstar** [comment]
Thank you for your reply. Also fixes the problem of installing 1.20. * version of numpy
