### ISSUE TITLE
np.bool is a deprecated alias for the builtin `bool`

### ISSUE THREAD

**Issue by sumiya-kuroda** [seung-lab/fill_voids#5]
Hi. I'm trying to fill some empty space of my segmented objects, but apparently there are some conflicts with latest numpy `numpy  == 1.21.0`. Here is the code I used,

```
filled = fill_voids.fill(my_segmented_objects, in_place=False)
```
and a message I got after that.
```
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
I actually got `filled`, but this was exactly as same as `my_segmented_objects`.

Thank you!

**Comment by william-silversmith** [comment]
Thanks for writing in! The numpy issue generates a warning, but shouldn't
affect the output. Are you sure the data do not have small defects that
make the holes actually connected to the exterior space?

If you share a small bit of data I could take a look.

**Comment by sumiya-kuroda** [comment]
You're right. Some of the empty spaces were successfully filled (not all of them actually). This would definitely help my analysis. Thank you so much for your support!!
