### ISSUE TITLE
upgrade pip precompiled for python 3.11

### ISSUE THREAD

**Issue by ashkanpakzad** [seung-lab/fill_voids#7]
Hi, great tool!

Unfortunately, there are breaking changes to install in python 3.11 and  `fill_voids.cpp` needs to be recompiled to install.

I'm not all that familiar with cython and C++ otherwise I would offer a pull request. I managed to install by cloning, deleting `fill_voids.cpp`, running the below from your comment
```bash
cython -3 --cplus fill_voids.pyx
```
and then install from local directory using pip.

It seems to work now. 👍🏽

**Comment by william-silversmith** [comment]
Will do!

**Comment by william-silversmith** [comment]
The new binaries have been on PyPI for a few days! Hope that helps. Thanks for reporting!
