### ISSUE TITLE
Can not import 2.0.4 - ModuleNotFoundError

### ISSUE THREAD

**Issue by Lauenburg** [seung-lab/fill_voids#8]
### System and Setup
- MacOS M1 Pro, 13.4 Venture
- Pyenv: 3.9.12
- Fresh pyenv-virtualenv env
- igneous-pipeline version: 4.18.0

### Issue
Calling `igneous image create <source> <target>` fails with the following error message:
```
File "/Users/lando/.pyenv/versions/3.9.12/lib/python3.9/site-packages/kimimaro/intake.py", line 38, in <module>
    import fill_voids
ModuleNotFoundError: No module named 'fill_voids'
```
However, fill_voids is installed. In the cell before it I run:
```
!pip install fill-voids
!pip list | grep fill-voids
```
which outputs
`fill-voids                     2.0.4`

Still, when trying to import fill_voids manually I got the same `ModuleNotFoundError` message. 

### Solution
Downgrading fill_voids solved the issue for me:
```
pip uninstall fill-voids -y
pip install fill-voids==2.0.3
```
Now the `igneous` call works as well as the manual import.

**Comment by william-silversmith** [comment]
Hi, I've deleted the broken wheel and am building a new release. Sorry
about that!

Will

**Comment by Lauenburg** [comment]
Awesome! Thank you, Will! I just loaded the newest version (2.0.5), and now it works!

**Comment by william-silversmith** [comment]
Fantastic! I'm glad it's working now. Happy coding!

Will
